name: Deploy to Servers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets[format('SERVER_IP_{0}', matrix.server)] }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            ls /var/www/html/githubaction