name: Deploy to Servers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.1
        with:
          ssh-password: ${{ secrets.SERVER_PASS }}
          server-ip: ${{ secrets[format('SERVER_IP_{0}', matrix.server)] }}
          server-port: 22
          server-username: ${{ secrets.SERVER_USER }}
          remote-dir: /var/www/html/githubaction